CREATE TABLE IF NOT EXISTS Users (
    id VARCHAR(35) PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS Groups (
    id VARCHAR(35) PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS UserGroups (
    id_user VARCHAR(35) UNIQUE NOT NULL,
    id_group VARCHAR(35) UNIQUE NOT NULL,
    PRIMARY KEY(id_user, id_group),
    FOREIGN KEY(id_user) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY(id_group) REFERENCES Groups(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS UserToken (
    id_user VARCHAR(35) PRIMARY KEY,
    token VARCHAR(100) UNIQUE NOT NULL,
    FOREIGN KEY(id_user) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Secrets (
    id VARCHAR(35) PRIMARY KEY,
    secret VARCHAR(200) NOT NULL DEFAULT ""
);

CREATE TABLE IF NOT EXISTS SecretUsers (
    id_user VARCHAR(35) UNIQUE NOT NULL,
    id_secret VARCHAR(35) UNIQUE NOT NULL,
    PRIMARY KEY(id_secret, id_user),
    FOREIGN KEY(id_secret) REFERENCES Secrets(id) ON DELETE CASCADE,
    FOREIGN KEY(id_user) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SecretGroups (
    id_group VARCHAR(35) UNIQUE NOT NULL,
    id_secret VARCHAR(35) UNIQUE NOT NULL,
    PRIMARY KEY(id_secret, id_group),
    FOREIGN KEY(id_secret) REFERENCES Secrets(id) ON DELETE CASCADE,
    FOREIGN KEY(id_group) REFERENCES Groups(id) ON DELETE CASCADE
);
