version: "3.9"
services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "nixpass"
      MYSQL_USER: "nixpass"
      MYSQL_PASSWORD: "N1xp4ss"
    ports:
      - 3306:3306
    volumes:
      - database_volume:/var/lib/mysql

volumes:
  database_volume:
  gpg_volume:
  jwt_volume:
